### ISSUE TITLE
no connection 

### ISSUE THREAD

**Issue by amerhwitat** [MultiChain/multichain-explorer-2#1]
Dears,

I have downloaded and started the explorer 2, I had python 3.9.5 , it gave me hard time with errors, so I downgraded to python 3.7.9 and the explorer is working but with this error when I try to connect to chain1 and chain2

> ----------------------------------------
> Exception happened during processing of request from ('192.168.8.102', 10142)
> Traceback (most recent call last):
>   File "C:\Program Files\Python37\lib\socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "C:\Program Files\Python37\lib\socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "C:\Program Files\Python37\lib\socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Program Files\Python37\lib\socketserver.py", line 720, in __init__
>     self.handle()
>   File "C:\Program Files\Python37\lib\http\server.py", line 426, in handle
>     self.handle_one_request()
>   File "C:\Program Files\Python37\lib\http\server.py", line 414, in handle_one_request
>     method()
>   File "C:\Users\Amer\Downloads\multichain-explorer-2-master\multichain-explorer-2-master\multichain-explorer-2\server.py", line 89, in do_GET
>     content=self.handler(self.chain,self.params,self.nparams)
>   File "C:\Users\Amer\Downloads\multichain-explorer-2-master\multichain-explorer-2-master\multichain-explorer-2\data.py", line 584, in handle_chains
>     native_flag=self.chain_native_flag(chain,response)
>   File "C:\Users\Amer\Downloads\multichain-explorer-2-master\multichain-explorer-2-master\multichain-explorer-2\data.py", line 539, in chain_native_flag
>     return chain.config['native-flag']
> KeyError: 'native-flag'
> ----------------------------------------

the browser hangs for a while and gives no connection in the state of connection, and I tried to revise everything from the config.ini to the node it self, I have chain1 and chain2 on the same server, I run only one instance at a time, this is for testing purposes as I'm new to multichain

**Comment by amerhwitat** [comment]
I have commented out the following in data.py

>         if response['result'] is not None:
>             if 'rewards' in response['result']:
>                 if response['result']['rewards'] > 0:
>                     chain.config['native-flag']=True
>                 else:
>                     chain.config['native-flag']=False
>             return chain.config['native-flag']

            
starting line 533 and the node is connected now, I have no antivirus problems and firewalls, checked the network multiple times

**Comment by gidgreen** [comment]
The Explorer requires MultiChain 2.2 beta 2 or later, which is not yet released :)
