### ISSUE TITLE
Fails with Python 3.8.x

### ISSUE THREAD

**Issue by chris-baumann-at** [MultiChain/multichain-explorer-2#2]
When running under Python 3.8.x the following error occurs:
ImportError: cannot import name 'escape' from 'cgi'

Solution: Replace 
`from cgi import escape`
with
`from html import escape`
in data.py and server.py

**Comment by gidgreen** [comment]
We're aware of this and will fix it in the next release. For now please see:

https://www.multichain.com/qa/38249/failing-run-the-new-explorer-am-fan-of-the-old-one-please-help?show=38249#q38249
