### ISSUE TITLE
Multichain-Explorer-2 Status No Connection

### ISSUE THREAD

**Issue by fzemenu** [MultiChain/multichain-explorer-2#3]
I have configured a blockchain by the name amazonchain on two AWS EC2 instances.
I can use Multichain-Webdemo as shown in the attached pdf file. Meaning my chain is up and running.
When I use Multichain-Explorer, I get Status No Connection and Multichain is not running messages on the page. See the attached pdf.
I have all the rpcuser, password, port, public ip address all set right. That's partly why Webdemo is working.
Can someone please throw some light why Explorer is giving me status no connection message?
Thank you
[Explorer Not Connected.pdf](https://github.com/MultiChain/multichain-explorer-2/files/7718569/Explorer.Not.Connected.pdf)

**Comment by gidgreen** [comment]
Please post the configuration files you have set up for the Web Demo and the Explorer, so we can compare and check them.

**Comment by fzemenu** [comment]
Thank you for the reply and offering to help.

I have copy pasted below the full text of the relevant files with the respective directories:
multichain.conf of my blockchain,    
config.txt  of multichain-web-demo,   and    
config.ini of multichain-explorer-2

Let me know if there is anything missing.
Thank you.

[ec2-user@ip-172-31-2-130 multichain-explorer-2]$ grep rpc-port ~/.multichain/amazonchain/params.dat
default-rpc-port = 4346 

[ec2-user@ip-172-31-2-130 amazonchain]$ pwd
/home/ec2-user/.multichain/amazonchain

#under above dirr (multichain.conf)
rpcuser=multichainrpc
rpcpassword=8zmfdMYrZjCrCRPMbMvxLZednSy2GWJh9232k5kjXaRW
rpcallowip=3.17.166.133


[ec2-user@ip-172-31-2-130 multichain-web-demo]$ pwd
/var/www/html/multichain-web-demo

#under above dir (config.txt)
default.name=FZtest1	# name to display in the web interface
default.rpchost=3.17.166.133	# IP address of MultiChain node
default.rpcsecure=0	# set to 1 to access RPC via https (e.g. for MultiChain on Azure)
default.rpcport=4346	# usually default-rpc-port from params.dat
default.rpcuser=multichainrpc	# username for RPC from multichain.conf
default.rpcpassword=8zmfdMYrZjCrCRPMbMvxLZednSy2GWJh9232k5kjXaRW	# password for RPC from multichain.conf


/home/ec2-user/multichain-explorer-2
[ec2-user@ip-172-31-2-130 multichain-explorer-2]$ 

#under above dir config.ini
[main]

# Who to accept connections from.
# You can only have one host entry in the config file otherwise the explorer will report an error.
# host=0.0.0.0          # to accept connections from anybody (including localhost) e.g. production
# host=localhost        # to only accept connections from your local machine e.g. testing

host=0.0.0.0

# Port to serve web pages

port=4444


[chains]

chain1=on
chain2=off

[chain1]

name=amazonchain

# The host serving MultiChain RPC, including scheme (e.g. "http://123.45.67.89"), default localhost ("http://127.0.0.1")

rpchost=3.17.166.133

# The RPC port MultiChain node listens to. Required for remote nodes.
# Optional for local nodes, default is taken from multichain.conf. If not found there - 'default-rpc-port' from params.dat
rpcport=4346

# The username for RPC calls. Required for remote nodes.
# Optional for local nodes, default is taken from multichain.conf. 
rpcuser=multichainrpc

# The password for RPC calls. Required for remote nodes.
# Optional for local nodes, default is taken from multichain.conf. 
rpcpassword=8zmfdMYrZjCrCRPMbMvxLZednSy2GWJh9232k5kjXaRW
# datadir=~/data/multichain/node1
#datadir=/home/ec2-user/.multichain/amazonchain

[chain2]

# name=chain2

**Comment by gidgreen** [comment]
You need to include the scheme prefix in `rpchost`, e.g.

`rpchost=http://3.17.166.133`

**Comment by fzemenu** [comment]
Thank you very much. 
You got it exactly right. 
Inserting "http://" before the public IP address changed the status on multichain-explorer-2 from "no connection" to "connected".
Thanks a lot again. Much appreciated.
