### ISSUE TITLE
UnboundLocalError for txid

### ISSUE THREAD

**Issue by DonMSimpson** [MultiChain/multichain-explorer-2#4]
Hi,

We are seeing multiple instances of the following message in our logs:

```
File "/root/multichain-explorer-2/data.py", line 1778, in handle_keyitems

return self.do_streamitems(chain,params,nparams,params[0],None,None,parse.unquote_plus(str(params[1])))

File "/root/multichain-explorer-2/data.py", line 1935, in do_streamitems

tx_html='<a href="' + chain.config['path-name'] + '/transaction/' + txid + '">' + txid[0:10]+ '...</a>'

UnboundLocalError: local variable 'txid' referenced before assignment
```

which appears to be from [here](https://github.com/MultiChain/multichain-explorer-2/blob/master/data.py#L1936) but the transaction id is not null, can you please advise?

**Comment by mike31** [comment]
Hi,

Are you sure you pulled the last changes? The commit https://github.com/MultiChain/multichain-explorer-2/commit/009c532b2cb129dd6a36b255b434813d76bc7823 fixes this issue. It also explains why you see the error on line 1935, nor 1936.

**Comment by DonMSimpson** [comment]
Sorry, yes it looks like we were using an outdated version, we have updated now and it's looking better, thank you!
