### ISSUE TITLE
Unable to see all Native Currency holders

### ISSUE THREAD

**Issue by lbunproject** [MultiChain/multichain-explorer-2#6]
I've noticed that whent he currency holder is greater than 20, I cannot get to the rest of the list. A "Page Not Found" is shown instead of getting a list of more holders.

Example explorer instance: 
http://147.182.214.238:4444/base_chain/assetholders/0-0-0

![image](https://github.com/MultiChain/multichain-explorer-2/assets/122697309/13354d16-51e1-4a36-8105-c534d0827c32)

**Comment by gidgreen** [comment]
Thanks, we'll take a look and revert shortly.

**Comment by mike31** [comment]
Fixed. Please pull the latest version.
